GoodFunGame/.idea/.idea.GoodFunGame/.idea/encodings.xml, GoodFunGame/.idea/.idea.GoodFunGame/.idea/indexLayout.xml, GoodFunGame/.idea/.idea.GoodFunGame/.idea/projectSettingsUpdater.xml, GoodFunGame/.idea/.idea.GoodFunGame/.idea/workspace.xml, GoodFunGame/Assets/Script.meta, GoodFunGame/Assets/Script/DataManager.cs, GoodFunGame/Assets/Script/DataManager.cs.meta, GoodFunGame/ProjectSettings/ProjectSettings.asset
Assets 
- Script 
--DataManager .cs 생성
- 데이터를 관리하기 위해서 생성한 스크립트 입니다.
=> [💫 Feature] 이정훈 DataManager 스크립트 생성 

GoodFunGame/Assets/Scripts/Datas/GameData.cs, GoodFunGame/Assets/Scripts/Datas/GameData.cs.meta, GoodFunGame/Assets/Scripts/Editor/DataParser.cs, GoodFunGame/Assets/Scripts/Managers/GameManager.cs, GoodFunGame/Assets/Scripts/Managers/GameManager.cs.meta, GoodFunGame/Assets/Scripts/Managers/Main.cs, GoodFunGame/Assets/Scripts/Scene/TestScene.cs
[스크립트 추가]
GameData.cs: 저장되어야 하는 게임 데이터 관리.
GameManager: 저장 및 로드, 초기화 및 데이터 접근.
[스크립트 변경]
DataParser: SaveData 삭제 기능 추가.
Main: GameManager 연결.
TestScene: 리소스 로드 후 GameManager 초기화.
=> [💫 Feature] Game SaveLoad Base

GoodFunGame/Assets/Scripts/Managers/DataManager.cs
Stage Data 호출 함수 
Main.data.Stages
=> [👨🏻‍🚒 HOT FIX] Stage Data Caller Method

GoodFunGame/Assets/Scripts/Managers/ObjectManager.cs, GoodFunGame/Assets/Scripts/Managers/ResourceManager.cs, GoodFunGame/Assets/Scripts/Models/Creature/Creature.cs, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/Creature/Thing.cs, GoodFunGame/Assets/Scripts/Scene/TestScene.cs, GoodFunGame/Assets/Scripts/Utility/AddressableAsset.cs
=> ObjectPooling Test

GoodFunGame/Assets/@Resources/Animations/Enemy/Enemy.controller, GoodFunGame/Assets/@Resources/Prefabs/TempEnemy.prefab, GoodFunGame/Assets/Scripts/Models/Creature/Creature.cs, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/Creature/Player.cs
Creatue의 OnHit 함수 구현 - Player, Enemy 상속 OnHit 구현
Enemy의 애니메이션이 local position에서 움직일 수 있도록 Prefab 변경
=> [Feature] Creature OnHit, Enemy Prefab modify

GoodFunGame/Assets/Scripts/Models/Creature/Player.cs
=> [BugFix] Player.cs

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Purchase.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Status.prefab, GoodFunGame/Assets/Scripts/Managers/GameManager.cs, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Purchase.cs, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Shop.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_SkillCard.cs
[UI_Popup_Purchase.cs]
- 스크립트 정리
- SkillCard UI 갱신을 위해 UI_SkillCard 참조할 수 있도록 함.
[UI_SkillCard.cs]
- 이 개체가 SkillData 정보를 가질 수 있도록 함.
- SetInfo와 Refresh 분리
[UI_Popup_Shop.cs]
- SetSkillCard()를 통해 SkillCard들을 생성하도록 변경.
[GameManager.cs]
- 스킬 구입 기능 추가
[UI_Popup_Status.prefab]
- UI 구성 레이아웃 변경
[UI_Popup_Purchase.prefab]
- UI 구성 레이아웃 변경
=> [➕ Improve]  Status, Purchase

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_GameOver.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Game.prefab, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/Creature/Player.cs, GoodFunGame/Assets/Scripts/Scene/GameScene.cs, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_GameOver.cs, GoodFunGame/Assets/Scripts/UI/Scene/UI_Scene_Game.cs
게임씬에 획득골드, 스코어 표시
게임오버 팝업에 스코어 골드 추가
적타격시 스코어점수 +1 죽일때 +50
=> [💫 Feature] GameScene Score Gold

GoodFunGame/Assets/@Resources/Prefabs/Projectiles/Projectile_TEMP.prefab, GoodFunGame/Assets/@Resources/Sprites/MWJ_Stage/Bullet_1_MWJ.png.meta, GoodFunGame/Assets/@Resources/Sprites/MWJ_Stage/Bullet_2_MWJ.png.meta, GoodFunGame/Assets/@Resources/Sprites/MWJ_Stage/Bullet_3_MWJ.png.meta, GoodFunGame/Assets/@Resources/Sprites/MWJ_Stage/Enemy_1_MWJ.png.meta, GoodFunGame/Assets/@Resources/Sprites/MWJ_Stage/Enemy_3_MWJ.png.meta, GoodFunGame/Assets/Scripts/Models/Creature/Creature.cs, GoodFunGame/Assets/Scripts/Models/Creature/Player.cs, GoodFunGame/Assets/Scripts/TEMP_/TempCharacter.cs, GoodFunGame/ProjectSettings/TagManager.asset
=> [Complex] MWJ Sprite Resize, Player.cs

GoodFunGame/Assets/@Resources/Animations/Explosion.anim, GoodFunGame/Assets/@Resources/Prefabs/TempEnemy.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Game.prefab, GoodFunGame/Assets/Scripts/Models/Creature/Creature.cs, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/Creature/Player.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_HeartIcon.cs, GoodFunGame/ProjectSettings/TagManager.asset
UI_Scene_Game의 하트 아이콘 Player Hp 와 연동
tag 추가 (PlayerProjectile, EnemyProjectile, Enemy)
Explosion 애니메이션이 재생된 후 안보이도록 수정
Enemy Prefab tag 변경 및 IsTrigger 체크
Enemy.cs OnCollision 이벤트 OnTrigger로 변경
=> [Complex] UI_Scene_Game Player Hp Integration, Add tags, Enemy Prefab, Explosion Anim Modify

GoodFunGame/Assets/AddressableAssetsData/AssetGroups/Prefabs.asset, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs
explosion이 생성되기 전에 Enemy가 Despawn되어 나오지 않던 버그 수정
Explosion Prefab, Addressable Group에 추가
=> [BugFix] Explosion bug fix

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Shop.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/SubItem/Shop_SkillCard.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/SubItem/UI_SkillEquip.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/SubItem/UI_SkillIcon.prefab, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Shop.cs, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Status.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_SkillCard.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_SkillEquip.cs
상점에서 구매한 스킬은 장비창에 장착버튼 활성화 됩니다 장착은 미구현입니다
=> 상점, 장비창 스킬 구매 연동

GoodFunGame/Assets/@Resources/Prefabs/Explosion.prefab, GoodFunGame/Assets/Scripts/Managers/ObjectManager.cs, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/Creature/Explosion.cs, GoodFunGame/Assets/Scripts/Models/Creature/Explosion.cs.meta
Explosion이 Despawn 되지 않는 이슈 수정
=> [BugFix] Explosion Pop bug fix

GoodFunGame/.idea/.idea.GoodFunGame/.idea/workspace.xml, GoodFunGame/Assets/@Resources/Prefabs/Player.prefab, GoodFunGame/Assets/@Resources/Prefabs/Projectiles/Projectile_TEMP.prefab, GoodFunGame/Assets/@Resources/Prefabs/Stages/BackGround.prefab, GoodFunGame/Assets/@Resources/Prefabs/TempEnemy.prefab, GoodFunGame/Assets/Scripts/InGame/Stage/StageBackGround.cs, GoodFunGame/Assets/Scripts/Models/Creature/Player.cs, GoodFunGame/ProjectSettings/Physics2DSettings.asset, GoodFunGame/ProjectSettings/TagManager.asset
[💫 Feature] Background Wall Collider
- 배경 콜라이더 생성하여 플레이어 이탈 방지
- 무적 상태 Bool 값으로 변경
=> [💫 Feature] Background Wall Collider

GoodFunGame/Assets/Scripts/Managers/ObjectManager.cs, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs, GoodFunGame/Assets/Scripts/Models/ProjectileGenerators/PG_Ring.cs, GoodFunGame/Assets/Scripts/Models/ProjectileGenerators/PG_Ring.cs.meta, GoodFunGame/Assets/Scripts/Models/Projectiles/Projectile.cs, GoodFunGame/Assets/Scripts/Scene/GameScene.cs, GoodFunGame/Assets/Scripts/UI/Extension.cs
패턴 추가
ObjectManage Enemies 리스트 public으로 변경
Extension IsValid 추가
최신화 하고 확인할수가 없음
=> [➕ Add] Pattern Projectile

GoodFunGame/Assets/Scripts/Models/Projectiles/Projectile.cs
중복처리 부분 추가
Addressable 에 개인 Sprite 추가
=> [➕ Add] Projectile_Despawn

GoodFunGame/Assets/Scripts/Models/Projectiles/Projectile.cs, GoodFunGame/Assets/Scripts/UI/Extension.cs
Despawn 안되던 점 수정
오류는 안 뜨는데 예외 처리 잘 되는지는 모르겠음
=> [🛠️ Bug Fix] Projectile_Despawn

GoodFunGame/Assets/@Resources/Animations/UI/NPC.controller, GoodFunGame/Assets/@Resources/Animations/UI/NPC.controller.meta, GoodFunGame/Assets/@Resources/Animations/UI/NPC_IDLE.anim, GoodFunGame/Assets/@Resources/Animations/UI/NPC_IDLE.anim.meta, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Option.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Purchase.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_SelectMenu.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Shop.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Status.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Main.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Title.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/SubItem/Option_Volume.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/SubItem/Shop_SkillCard.prefab, GoodFunGame/Assets/@Resources/UI_Assets/ResourcesData/Sprite/Component/Frame/Frame_ItemFrame01_Color_Green.png.meta, GoodFunGame/Assets/@Resources/UI_Assets/ResourcesData/Sprite/Component/Frame/Frame_ItemFrame01_Color_Yellow.png.meta, GoodFunGame/Assets/@Resources/UI_Assets/ResourcesData/Sprite/Component/Label/Label_SpeechBubbleLabel02.png.meta, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Status.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_SkillCard.cs
=> UI 이미지들 조금 수정했습니다.

GoodFunGame/Assets/AddressableAssetsData/AssetGroups/Sprites.asset
=> [🛠️ Bug Fix] Address Name

GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/Boss_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/Bullet_1_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/Bullet_2_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/Bullet_3_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/SOLDIER1_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/SOLDIER2_CHH.png.meta, GoodFunGame/Assets/@Resources/Sprites/CHH_Stage/SOLDIER3_CHH.png.meta, GoodFunGame/Assets/AddressableAssetsData/AddressableAssetSettings.asset
=> [❗️Complex] CHH_Sprite_Size

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Pause.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Game.prefab, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Pause.cs
=> [➕ Add] UI image Update

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_Status.prefab, GoodFunGame/Assets/@Resources/Prefabs/UI/Scene/UI_Scene_Game.prefab, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Shop.cs, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_Status.cs, GoodFunGame/Assets/Scripts/UI/Scene/UI_Scene_Game.cs
전투씬 스킬 단축키 위에 해당 스킬 이미지 뜨도록 추가.
해당 스킬 이미지로 바꾸는건 미구현
=> [💫 Feature] Batlle Scene + Skill Icon

GoodFunGame/Assets/Scripts/Scene/TitleScene.cs, GoodFunGame/Assets/Scripts/UI/SubItem/UI_SkillCard.cs
=> [🛠️ Bug Fix] Gold fix

GoodFunGame/Assets/@Resources/Sprites/Skill/bounce.physicsMaterial2D, GoodFunGame/Assets/Scripts/Models/Skills/Skill_AutoTarget.cs, GoodFunGame/Assets/Scripts/Models/Skills/Skill_EnergyBurst.cs, GoodFunGame/Assets/Scripts/Models/Skills/Skill_HomigMissile.cs, GoodFunGame/Assets/Scripts/Models/Skills/Skill_HomigMissileObject.cs, GoodFunGame/Assets/Scripts/Models/Skills/Skill_PiercingShotObject.cs
=> [Complex] Skill modify

GoodFunGame/Assets/@JsonData/SkillData.json, GoodFunGame/Assets/Scripts/Models/Creature/Enemy.cs
=> [➕ Add] Score, Gold Value Change

GoodFunGame/Assets/@Resources/Prefabs/UI/Popup/UI_Popup_GameEnd_Clear.prefab, GoodFunGame/Assets/Scripts/UI/Popup/UI_Popup_GameEnd_Clear.cs
=> [🛠️ Bug Fix] useless delete
